# -*- coding: utf-8 -*-
"""Artificial Neaural Networks_DL_churn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHRwhbr-a11_QwJVMtUC9wuwTRCkHHNM
"""

import pandas as pd

df=pd.read_csv("/content/Churn.csv")

df.sample(5)

df.duplicated().sum()

df.Geography.unique()

df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

df.head()

x = df.drop(['Exited'],axis=1)  #x = df.drop(colums=['Exited'])
y = df['Exited']

y

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=100)

x_train.shape,x_test.shape,y_train.shape,y_test.shape

sc=StandardScaler()
train_x_scal = sc.fit_transform(x_train)  # here it does't need to scale y
test_x_scal = sc.transform(x_test)

import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(11,activation='relu',input_dim=11))   # input layer
model.add(Dense(11,activation='relu'))   # hidden layer
model.add(Dense(1,activation='sigmoid')) # output layer
model.summary()

model.compile(loss='binary_crossentropy', optimizer='Adam',metrics=['accuracy'])

hist = model.fit(train_x_scal,y_train,epochs=20,validation_split=0.2)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.plot(hist.history['loss'])
plt.plot(hist.history['val_loss'])   # validation loss
plt.show()

plt.plot(hist.history['accuracy'])
plt.plot(hist.history['val_accuracy'])
plt.show()

import numpy as np

y_pred = np.where

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)